#include "uefi_image_auth.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* ================================================================
 * L5: Complete implementations of CRC32 and SHA-256
 *
 * CRC32: table-driven algorithm using IEEE 802.3 polynomial
 *        0xEDB88320 (reflected form of 0x04C11DB7).
 *        Complexity: O(n) time, O(256*4) space.
 *
 * SHA-256: Full FIPS 180-4 implementation with:
 *   - Merkle-Damgard iterative construction
 *   - 64-round compression function
 *   - Message schedule expansion (sigma0/sigma1, Sigma0/Sigma1)
 *   - Proper padding per section 5.1.1 (append 1, pad 0s, append 64-bit length)
 *   Complexity: O(n) time, O(64*4 + 8*4) space per block.
 * ================================================================ */

/* ================================================================
 * CRC32 Implementation
 *
 * Theorem: For an n-bit CRC with generator polynomial G(x),
 * CRC(M) mod G(x) detects:
 *   - All single-bit errors
 *   - All double-bit errors (if n > period of (x+1))
 *   - All odd-number bit errors (if (x+1) | G(x))
 *   - All burst errors <= n bits
 * Reference: Peterson & Brown, "Cyclic Codes for Error Detection",
 *            Proc. IRE, 1961. Also: IEEE 802.3-2018 Clause 3.2.8.
 * ================================================================ */

/* Pre-computed CRC32 lookup table (polynomial 0xEDB88320).
 * Each entry t[i] = CRC32 of the byte i, accumulated.
 * Generated by: for i in 0..255: t[i] = reflect(i) >> 24, process 8 bits. */

static uint32_t g_crc32_table[256];
static bool     g_crc32_table_ready = false;

static void crc32_build_table(void) {
    if (g_crc32_table_ready) return;
    for (uint32_t i = 0; i < 256; i++) {
        uint32_t crc = i;
        for (int j = 0; j < 8; j++) {
            if (crc & 1)
                crc = (crc >> 1) ^ CRC32_POLYNOMIAL;
            else
                crc = crc >> 1;
        }
        g_crc32_table[i] = crc;
    }
    g_crc32_table_ready = true;
}

uint32_t crc32_init(void) {
    crc32_build_table();
    return CRC32_INITIAL;
}

uint32_t crc32_update(uint32_t crc, const uint8_t *data, size_t len) {
    crc32_build_table();
    if (!data || len == 0) return crc;
    for (size_t i = 0; i < len; i++) {
        crc = g_crc32_table[(crc ^ data[i]) & 0xFF] ^ (crc >> 8);
    }
    return crc;
}

uint32_t crc32_finalize(uint32_t crc) {
    return crc ^ CRC32_FINAL_XOR;
}

uint32_t crc32_compute(const uint8_t *data, size_t len) {
    uint32_t crc = crc32_init();
    crc = crc32_update(crc, data, len);
    return crc32_finalize(crc);
}

/* ================================================================
 * SHA-256 Implementation (FIPS PUB 180-4)
 *
 * The SHA-256 algorithm takes a message of length < 2^64 bits and
 * produces a 256-bit (32-byte) message digest.
 *
 * Preprocessing:
 *   1. Pad the message: append bit '1', then k zero bits, then 64-bit
 *      big-endian length. k = smallest non-negative solution to
 *      (len + 1 + k) mod 512 = 448.
 *   2. Parse into N 512-bit blocks M^(1)...M^(N).
 *
 * Hash computation (Merkle-Damgard strengthening):
 *   H0^(0) = IV (initial hash value per FIPS 180-4 §5.3.3)
 *   For i = 1 to N:
 *     H^(i) = H^(i-1) + SHA256_Compress(M^(i), H^(i-1))
 *   Result = H^(N)
 * ================================================================ */

/* Initial hash values (first 32 bits of fractional parts
 * of square roots of first 8 primes: 2..19) */
static const uint32_t g_sha256_iv[8] = {
    0x6A09E667UL, 0xBB67AE85UL, 0x3C6EF372UL, 0xA54FF53AUL,
    0x510E527FUL, 0x9B05688CUL, 0x1F83D9ABUL, 0x5BE0CD19UL
};

/* Round constants (first 32 bits of fractional parts
 * of cube roots of first 64 primes: 2..311) */
static const uint32_t g_sha256_k[64] = {
    0x428A2F98UL, 0x71374491UL, 0xB5C0FBCFUL, 0xE9B5DBA5UL,
    0x3956C25BUL, 0x59F111F1UL, 0x923F82A4UL, 0xAB1C5ED5UL,
    0xD807AA98UL, 0x12835B01UL, 0x243185BEUL, 0x550C7DC3UL,
    0x72BE5D74UL, 0x80DEB1FEUL, 0x9BDC06A7UL, 0xC19BF174UL,
    0xE49B69C1UL, 0xEFBE4786UL, 0x0FC19DC6UL, 0x240CA1CCUL,
    0x2DE92C6FUL, 0x4A7484AAUL, 0x5CB0A9DCUL, 0x76F988DAUL,
    0x983E5152UL, 0xA831C66DUL, 0xB00327C8UL, 0xBF597FC7UL,
    0xC6E00BF3UL, 0xD5A79147UL, 0x06CA6351UL, 0x14292967UL,
    0x27B70A85UL, 0x2E1B2138UL, 0x4D2C6DFCUL, 0x53380D13UL,
    0x650A7354UL, 0x766A0ABBUL, 0x81C2C92EUL, 0x92722C85UL,
    0xA2BFE8A1UL, 0xA81A664BUL, 0xC24B8B70UL, 0xC76C51A3UL,
    0xD192E819UL, 0xD6990624UL, 0xF40E3585UL, 0x106AA070UL,
    0x19A4C116UL, 0x1E376C08UL, 0x2748774CUL, 0x34B0BCB5UL,
    0x391C0CB3UL, 0x4ED8AA4AUL, 0x5B9CCA4FUL, 0x682E6FF3UL,
    0x748F82EEUL, 0x78A5636FUL, 0x84C87814UL, 0x8CC70208UL,
    0x90BEFFFAUL, 0xA4506CEBUL, 0xBEF9A3F7UL, 0xC67178F2UL
};

/* SHA-256 logical functions per FIPS 180-4 §4.1.2 */
#define ROTR32(x, n) (((x) >> (n)) | ((x) << (32 - (n))))
#define SHR32(x, n)  ((x) >> (n))

#define CH(x, y, z)  (((x) & (y)) ^ (~(x) & (z)))
#define MAJ(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define BSIG0(x)     (ROTR32(x,  2) ^ ROTR32(x, 13) ^ ROTR32(x, 22))
#define BSIG1(x)     (ROTR32(x,  6) ^ ROTR32(x, 11) ^ ROTR32(x, 25))
#define SSIG0(x)     (ROTR32(x,  7) ^ ROTR32(x, 18) ^ SHR32(x,  3))
#define SSIG1(x)     (ROTR32(x, 17) ^ ROTR32(x, 19) ^ SHR32(x, 10))

/* Process one 512-bit block.
 * Input: 64-byte block + current 8-word hash state.
 * Performs 64 rounds of compression.
 * Data schedule W[0..15] expanded to W[16..63]. */
static void sha256_compress_block(uint32_t state[8], const uint8_t block[64]) {
    uint32_t w[64];
    uint32_t a, b, c, d, e, f, g, h;

    /* Prepare message schedule W[0..15] (big-endian from block) */
    for (int i = 0; i < 16; i++) {
        w[i] = ((uint32_t)block[i * 4 + 0] << 24) |
               ((uint32_t)block[i * 4 + 1] << 16) |
               ((uint32_t)block[i * 4 + 2] << 8)  |
               ((uint32_t)block[i * 4 + 3]);
    }
    /* Extend to W[16..63] */
    for (int i = 16; i < 64; i++) {
        w[i] = SSIG1(w[i - 2]) + w[i - 7] + SSIG0(w[i - 15]) + w[i - 16];
    }

    a = state[0]; b = state[1]; c = state[2]; d = state[3];
    e = state[4]; f = state[5]; g = state[6]; h = state[7];

    /* 64 rounds of compression */
    for (int i = 0; i < 64; i++) {
        uint32_t t1 = h + BSIG1(e) + CH(e, f, g) + g_sha256_k[i] + w[i];
        uint32_t t2 = BSIG0(a) + MAJ(a, b, c);
        h = g; g = f; f = e; e = d + t1;
        d = c; c = b; b = a; a = t1 + t2;
    }

    state[0] += a; state[1] += b; state[2] += c; state[3] += d;
    state[4] += e; state[5] += f; state[6] += g; state[7] += h;
}

void sha256_init(SHA256Context *ctx) {
    if (!ctx) return;
    for (int i = 0; i < 8; i++) ctx->state[i] = g_sha256_iv[i];
    ctx->total_bytes = 0;
    ctx->buffer_used = 0;
    ctx->finalized   = false;
}

void sha256_update(SHA256Context *ctx, const uint8_t *data, size_t len) {
    if (!ctx || !data || len == 0 || ctx->finalized) return;

    ctx->total_bytes += len;

    /* Process complete blocks from buffer + new data */
    while (len > 0) {
        size_t space = SHA256_BLOCK_SIZE - ctx->buffer_used;
        size_t copy  = (len < space) ? len : space;
        memcpy(ctx->buffer + ctx->buffer_used, data, copy);
        ctx->buffer_used += (uint8_t)copy;
        data += copy;
        len  -= copy;

        if (ctx->buffer_used == SHA256_BLOCK_SIZE) {
            sha256_compress_block(ctx->state, ctx->buffer);
            ctx->buffer_used = 0;
        }
    }
}

void sha256_finalize(SHA256Context *ctx, uint8_t digest[SHA256_DIGEST_SIZE]) {
    if (!ctx || !digest || ctx->finalized) return;
    ctx->finalized = true;

    uint64_t total_bits = ctx->total_bytes * 8;

    /* Append bit '1' (0x80) */
    ctx->buffer[ctx->buffer_used++] = 0x80;

    /* Pad with zeros until 56 bytes mod 64 (448 bits) */
    if (ctx->buffer_used > 56) {
        memset(ctx->buffer + ctx->buffer_used, 0,
               SHA256_BLOCK_SIZE - ctx->buffer_used);
        sha256_compress_block(ctx->state, ctx->buffer);
        ctx->buffer_used = 0;
    }
    memset(ctx->buffer + ctx->buffer_used, 0,
           (size_t)(56 - ctx->buffer_used));

    /* Append 64-bit big-endian length */
    ctx->buffer[56] = (uint8_t)(total_bits >> 56);
    ctx->buffer[57] = (uint8_t)(total_bits >> 48);
    ctx->buffer[58] = (uint8_t)(total_bits >> 40);
    ctx->buffer[59] = (uint8_t)(total_bits >> 32);
    ctx->buffer[60] = (uint8_t)(total_bits >> 24);
    ctx->buffer[61] = (uint8_t)(total_bits >> 16);
    ctx->buffer[62] = (uint8_t)(total_bits >> 8);
    ctx->buffer[63] = (uint8_t)(total_bits);

    sha256_compress_block(ctx->state, ctx->buffer);

    /* Output big-endian digest */
    for (int i = 0; i < 8; i++) {
        digest[i * 4 + 0] = (uint8_t)(ctx->state[i] >> 24);
        digest[i * 4 + 1] = (uint8_t)(ctx->state[i] >> 16);
        digest[i * 4 + 2] = (uint8_t)(ctx->state[i] >> 8);
        digest[i * 4 + 3] = (uint8_t)(ctx->state[i]);
    }
}

void sha256_hash(const uint8_t *data, size_t len,
                  uint8_t digest[SHA256_DIGEST_SIZE]) {
    SHA256Context ctx;
    sha256_init(&ctx);
    sha256_update(&ctx, data, len);
    sha256_finalize(&ctx, digest);
}

void sha256_hash_to_hex(const uint8_t *data, size_t len,
                         char *hex_out, size_t hex_size) {
    if (!data || !hex_out || hex_size < (SHA256_DIGEST_SIZE * 2 + 1)) return;
    uint8_t digest[SHA256_DIGEST_SIZE];
    sha256_hash(data, len, digest);
    for (int i = 0; i < SHA256_DIGEST_SIZE; i++) {
        int written = snprintf(hex_out + (size_t)(i * 2), 3, "%02x", digest[i]);
        if (written < 0) { hex_out[0] = '\0'; return; }
    }
    hex_out[SHA256_DIGEST_SIZE * 2] = '\0';
}

/* ================================================================
 * Secure Boot Variable Infrastructure
 *
 * UEFI Secure Boot signing chain:
 *   PK (Platform Key) signs KEK
 *   KEK (Key Exchange Key) signs db and dbx
 *   db (Authorized DB) contains allowed certs/hashes
 *   dbx (Forbidden DB) contains revoked certs/hashes
 *
 * Image verification flow:
 *   EFI binary -> PE/COFF signature -> check against db (allow)
 *                                  -> check against dbx (deny if found)
 *                                  -> check KEK-signed timestamp
 * Reference: UEFI Specification 2.10 §32.4
 * ================================================================ */

static const SecureBootVarInfo g_sb_var_info[] = {
    {SB_VAR_PK,  "PK",  "{8BE4DF61-93CA-11D2-AA0D-00E098032B8C}", true},
    {SB_VAR_KEK, "KEK", "{8BE4DF61-93CA-11D2-AA0D-00E098032B8C}", true},
    {SB_VAR_DB,  "db",  "{d719b2cb-3d3a-4596-a3bc-dad00e67656f}", true},
    {SB_VAR_DBX, "dbx", "{d719b2cb-3d3a-4596-a3bc-dad00e67656f}", true},
    {SB_VAR_DBT, "dbt", "{d719b2cb-3d3a-4596-a3bc-dad00e67656f}", true},
    {SB_VAR_DBR, "dbr", "{d719b2cb-3d3a-4596-a3bc-dad00e67656f}", true},
};

void secure_boot_init(SecureBootState *sb) {
    if (!sb) return;
    memset(sb, 0, sizeof(SecureBootState));
    sb->setup_mode = true;
    sb->secure_boot_enabled = false;
    printf("  SecureBoot: initialized (Setup Mode, SB disabled)\n");
}

const char *secure_boot_variable_name(SecureBootVariableId id) {
    if ((size_t)id >= SB_VAR_COUNT) return "Unknown";
    return g_sb_var_info[id].name;
}

/* Simulate image verification: compute hash, check against known
 * allow/deny lists. In production, this involves X.509 certificate
 * parsing and RSA-2048+ signature verification over Authenticode. */
bool secure_boot_verify_image(const SecureBootState *sb,
                               const uint8_t *image, size_t size,
                               const uint8_t *signature, size_t sig_size) {
    if (!sb || !image) return false;

    if (!sb->secure_boot_enabled) {
        printf("  SecureBoot: disabled, bypassing verification\n");
        return true;
    }

    printf("  SecureBoot: verifying image (%zu bytes, sig=%zu bytes)\n",
           size, sig_size);

    /* Compute PE hash */
    uint8_t pe_hash[SHA256_DIGEST_SIZE];
    sha256_hash(image, size, pe_hash);

    /* Check dbx (deny list) first */
    if (sb->dbx_present) {
        printf("  SecureBoot: checking dbx...\n");
    }

    /* Check db (allow list) */
    if (sb->db_present) {
        printf("  SecureBoot: checking db...\n");
        /* In real implementation: iterate db entries, verify
         * signature chain KEK -> db entry -> image signature */
        char hex_hash[65];
        sha256_hash_to_hex(image, size, hex_hash, sizeof(hex_hash));
        printf("  SecureBoot: image SHA-256 = %s\n", hex_hash);
        (void)signature; (void)sig_size;
        return true;
    }

    printf("  SecureBoot: no db, rejecting image\n");
    return false;
}

void secure_boot_print_state(const SecureBootState *sb) {
    if (!sb) return;
    printf("\n=== Secure Boot State ===\n");
    printf("  Setup Mode:         %s\n", sb->setup_mode ? "YES" : "NO");
    printf("  Secure Boot:        %s\n", sb->secure_boot_enabled ? "ENABLED" : "DISABLED");
    printf("  Audit Mode:         %s\n", sb->audit_mode ? "YES" : "NO");
    printf("  Deployed Mode:      %s\n", sb->deployed_mode ? "YES" : "NO");
    printf("  PK Present:         %s\n", sb->pk_present ? "YES" : "NO");
    printf("  KEK Present:        %s\n", sb->kek_present ? "YES" : "NO");
    printf("  db Present:         %s\n", sb->db_present ? "YES" : "NO");
    printf("  dbx Present:        %s\n", sb->dbx_present ? "YES" : "NO");
}

/* ================================================================
 * Capsule Update (UEFI Specification 2.10 §8.5)
 *
 * Firmware update via capsule: signed binary blob containing
 * new firmware images, processed by UpdateCapsule() runtime service.
 * Capsule format: EFI_CAPSULE_HEADER + capsule body + optional payloads.
 * ================================================================ */

bool capsule_parse_header(const uint8_t *data, size_t size,
                           EFICapsuleHeader *hdr) {
    if (!data || !hdr || size < sizeof(EFICapsuleHeader)) return false;
    memcpy(hdr, data, sizeof(EFICapsuleHeader));
    return true;
}

bool capsule_validate_header(const EFICapsuleHeader *hdr, size_t total_size) {
    if (!hdr) return false;
    if (hdr->header_size < sizeof(EFICapsuleHeader)) {
        printf("  Capsule: header_size=%u < minimum %zu\n",
               hdr->header_size, sizeof(EFICapsuleHeader));
        return false;
    }
    if (hdr->capsule_image_size > total_size) {
        printf("  Capsule: image_size=%u > total_size=%zu\n",
               hdr->capsule_image_size, total_size);
        return false;
    }
    return true;
}

void capsule_print_header(const EFICapsuleHeader *hdr) {
    if (!hdr) return;
    printf("\n=== EFI Capsule Header ===\n");
    printf("  Header Size:      %u bytes\n", hdr->header_size);
    printf("  Flags:            0x%08X\n", hdr->flags);
    if (hdr->flags & 0x00010000) printf("    [PERSIST_ACROSS_RESET]\n");
    if (hdr->flags & 0x00020000) printf("    [POPULATE_SYSTEM_TABLE]\n");
    if (hdr->flags & 0x00040000) printf("    [INITIATE_RESET]\n");
    printf("  Image Size:       %u bytes\n", hdr->capsule_image_size);
    printf("  Capsule GUID:     ");
    for (int i = 0; i < 16; i++) printf("%02X", hdr->capsule_guid[i]);
    printf("\n");
}

/* ================================================================
 * EFI Time
 * ================================================================ */

void efi_time_init(EFITime *t, uint16_t year, uint8_t month, uint8_t day,
                    uint8_t hour, uint8_t minute, uint8_t second) {
    if (!t) return;
    memset(t, 0, sizeof(EFITime));
    t->year       = year;
    t->month      = month;
    t->day        = day;
    t->hour       = hour;
    t->minute     = minute;
    t->second     = second;
    t->nanosecond = 0;
    t->timezone   = 0;
    t->daylight   = 0;
}