#ifndef ACPI_FW_H
#define ACPI_FW_H

/*
 * acpi_fw.h ? ACPI Table Generation in Firmware
 *
 * Implements core ACPI (Advanced Configuration and Power Interface)
 * table structures as generated by firmware during boot.
 *
 * References:
 *   - ACPI Specification v6.5 (UEFI Forum, 2022)
 *   - Intel Platform Innovation Framework for ACPI
 *   - ARM SBBR (Server Base Boot Requirements) ACPI requirements
 *
 * Knowledge coverage:
 *   L1: RSDP, XSDT, FADT, MADT, DSDT struct definitions
 *   L2: ACPI table enumeration and namespace concept
 *   L3: Multi-table construction pipeline with checksums
 *   L4: ACPI specification compliance verification
 *   L7: OS-provided hardware enumeration via ACPI
 *   L8: ACPI vs Device Tree comparison for ARM platforms
 */

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

#define ACPI_MAX_TABLES    32
#define ACPI_OEM_ID_LEN    6
#define ACPI_OEM_TABLE_LEN 8
#define ACPI_NAME_LEN      4

/* ??? L1: Root System Description Pointer (RSDP) ??????????????????? */

/*
 * RSDP is located by the OS via:
 *   - x86: EBDA (Extended BIOS Data Area) or 0x000E0000-0x000FFFFF
 *   - ARM: Passed via UEFI configuration table or device tree
 */
typedef struct {
    char     signature[8];        /* "RSD PTR "                  */
    uint8_t  checksum;            /* Sum of bytes 0..19 == 0     */
    char     oem_id[ACPI_OEM_ID_LEN];
    uint8_t  revision;            /* 0 = ACPI 1.0, 2 = ACPI 2.0+ */
    uint32_t rsdt_address;        /* 32-bit RSDT pointer (v1.0) */
    /* Fields below only valid for ACPI 2.0+ (revision >= 2) */
    uint32_t length;
    uint64_t xsdt_address;        /* 64-bit XSDT pointer         */
    uint8_t  extended_checksum;   /* Sum of entire table == 0    */
    uint8_t  reserved[3];
} ACPIRSDP;

/* ??? L1: System Description Table Header ??????????????????????????? */

/*
 * Every ACPI table begins with this common header.
 * The Signature identifies the table type (e.g., "FACP" = FADT).
 */
typedef struct {
    char     signature[ACPI_NAME_LEN];
    uint32_t length;              /* Total table length incl. header */
    uint8_t  revision;
    uint8_t  checksum;            /* Sum of all bytes == 0           */
    char     oem_id[ACPI_OEM_ID_LEN];
    char     oem_table_id[ACPI_OEM_TABLE_LEN];
    uint32_t oem_revision;
    uint32_t creator_id;
    uint32_t creator_revision;
} ACPISDTHeader;

/* ??? L1: Extended System Description Table (XSDT) ????????????????? */

/*
 * XSDT (preferred over RSDT for 64-bit systems) is an array of
 * 64-bit pointers to other ACPI tables.
 */
typedef struct {
    ACPISDTHeader header;
    uint64_t      table_entries[ACPI_MAX_TABLES];
} ACPIXSDT;

/* ??? L1: Fixed ACPI Description Table (FADT / "FACP") ?????????????? */

typedef struct {
    uint8_t  address_space_id;    /* 0=System Memory, 1=System I/O */
    uint8_t  register_bit_width;
    uint8_t  register_bit_offset;
    uint8_t  access_size;
    uint64_t address;
} ACPIGenericAddress;

typedef struct {
    ACPISDTHeader       header;
    uint32_t            firmware_ctrl;       /* 32-bit FACS pointer */
    uint32_t            dsdt;                /* 32-bit DSDT pointer */
    uint8_t             reserved1;
    uint8_t             preferred_pm_profile; /* 1=Desktop, 2=Mobile, etc. */
    uint16_t            sci_interrupt;
    uint32_t            smi_command_port;
    uint8_t             acpi_enable;
    uint8_t             acpi_disable;
    uint8_t             s4bios_req;
    uint8_t             pstate_control;
    uint32_t            pm1a_event_block;
    uint32_t            pm1b_event_block;
    uint32_t            pm1a_control_block;
    uint32_t            pm1b_control_block;
    uint32_t            pm2_control_block;
    uint32_t            pm_timer_block;
    uint32_t            gpe0_block;
    uint32_t            gpe1_block;
    uint8_t             pm1_event_length;
    uint8_t             pm1_control_length;
    uint8_t             pm2_control_length;
    uint8_t             pm_timer_length;
    uint8_t             gpe0_block_length;
    uint8_t             gpe1_block_length;
    uint8_t             gpe1_base;
    uint8_t             cstate_control;
    uint16_t            worst_c2_latency;
    uint16_t            worst_c3_latency;
    uint16_t            flush_size;
    uint16_t            flush_stride;
    uint8_t             duty_offset;
    uint8_t             duty_width;
    uint8_t             day_alarm;
    uint8_t             month_alarm;
    uint8_t             century;
    uint16_t            boot_architecture_flags;
    uint8_t             reserved2;
    uint32_t            flags;
    ACPIGenericAddress  reset_register;
    uint8_t             reset_value;
    uint16_t            arm_boot_arch;        /* ARM-specific */
    uint8_t             fadt_minor_version;
    uint64_t            x_firmware_ctrl;
    uint64_t            x_dsdt;
    ACPIGenericAddress  x_pm1a_event_block;
    ACPIGenericAddress  x_pm1b_event_block;
    ACPIGenericAddress  x_pm1a_control_block;
    ACPIGenericAddress  x_pm1b_control_block;
    ACPIGenericAddress  x_pm2_control_block;
    ACPIGenericAddress  x_pm_timer_block;
    ACPIGenericAddress  x_gpe0_block;
    ACPIGenericAddress  x_gpe1_block;
    ACPIGenericAddress  sleep_control_register;
    ACPIGenericAddress  sleep_status_register;
    uint64_t            hypervisor_vendor_id;
} ACPIFADT;

/* ??? L1: Multiple APIC Description Table (MADT / "APIC") ???????????? */

typedef enum {
    MADT_TYPE_LAPIC          = 0,   /* Local APIC                 */
    MADT_TYPE_IOAPIC         = 1,   /* I/O APIC                   */
    MADT_TYPE_INTERRUPT_SRC  = 2,   /* Interrupt Source Override  */
    MADT_TYPE_NMI_SOURCE     = 3,   /* NMI Source                 */
    MADT_TYPE_LAPIC_NMI      = 4,   /* Local APIC NMI             */
    MADT_TYPE_LAPIC_ADDR_OVR = 5,   /* Local APIC Address Override */
    MADT_TYPE_IOSAPIC        = 6,   /* I/O SAPIC                  */
    MADT_TYPE_LOCAL_SAPIC    = 7,   /* Local SAPIC                */
    MADT_TYPE_GICC           = 11,  /* ARM Generic Interrupt CPU  */
    MADT_TYPE_GICD           = 12,  /* ARM GIC Distributor        */
    MADT_TYPE_GIC_MSI_FRAME  = 13,  /* ARM GIC MSI Frame          */
    MADT_TYPE_GICR           = 14,  /* ARM GIC Redistributor      */
    MADT_TYPE_GIC_ITS        = 15   /* ARM GIC ITS                */
} MADTEntryType;

typedef struct {
    uint8_t  type;
    uint8_t  length;
} MADTEntryHeader;

typedef struct {
    MADTEntryHeader header;
    uint8_t         acpi_processor_id;
    uint8_t         apic_id;
    uint32_t        flags;          /* bit0=Enabled */
} MADTLapic;

typedef struct {
    MADTEntryHeader header;
    uint8_t         ioapic_id;
    uint8_t         reserved;
    uint32_t        ioapic_address;
    uint32_t        global_sys_interrupt_base;
} MADTIoapic;

typedef struct {
    MADTEntryHeader header;
    uint16_t        reserved;
    uint64_t        physical_base_addr;
} MADTGicd;

typedef struct {
    ACPISDTHeader   header;
    uint32_t        local_apic_address;
    uint32_t        flags;          /* bit0=PCAT_COMPAT (dual 8259) */
    /* Followed by variable-length MADT entries */
    uint8_t         entries[];
} ACPIMADT;

/* ??? L1: Differentiated System Description Table (DSDT) ???????????? */

/*
 * DSDT contains AML (ACPI Machine Language) bytecode.
 * It defines the platform's device hierarchy and power management objects.
 * For simulation, we store minimal AML bytecode.
 */
typedef struct {
    ACPISDTHeader header;
    uint8_t       aml_data[];
} ACPIDSDT;

/* ??? L1: Secondary System Description Table (SSDT) ????????????????? */

typedef struct {
    ACPISDTHeader header;
    uint8_t       aml_data[];
} ACPISSDT;

/* ??? L3: ACPI Table Manager ????????????????????????????????????????? */

typedef struct {
    ACPIRSDP    rsdp;
    ACPIXSDT    xsdt;
    void       *table_ptrs[ACPI_MAX_TABLES];
    uint32_t    table_count;
    ACPIFADT    fadt;
    /* ACPI namespace root */
    char        oem_id[ACPI_OEM_ID_LEN + 1];
    char        oem_table_id[ACPI_OEM_TABLE_LEN + 1];
} ACPIManager;

/* ??? L2/L3: ACPI API ??????????????????????????????????????????????? */

/* Initialize the ACPI table manager with OEM identification */
bool acpi_init(ACPIManager *mgr, const char *oem_id, const char *oem_table_id);

/* Add a table to the XSDT (returns false if table limit reached) */
bool acpi_add_table(ACPIManager *mgr, ACPISDTHeader *table);

/* Compute and fill in the checksum for any ACPI table */
void acpi_set_checksum(ACPISDTHeader *table);

/* Validate all checksums in the table set */
bool acpi_validate_checksums(const ACPIManager *mgr);

/* Build a complete FADT (Fixed ACPI Description Table) */
bool acpi_build_fadt(ACPIManager *mgr, uint8_t pm_profile,
                     uint16_t sci_irq, uint32_t flags);

/* Build a MADT with specified local APIC / GIC entries */
bool acpi_build_madt_lapic(ACPIManager *mgr, uint32_t local_apic_base,
                           uint8_t cpu_count, const uint8_t *apic_ids);

/* Build a MADT for ARM GICv3 systems */
bool acpi_build_madt_gic(ACPIManager *mgr, uint64_t gicd_base,
                         uint64_t gicr_base, uint8_t cpu_count);

/* Build a minimal DSDT with AML header */
bool acpi_build_dsdt(ACPIManager *mgr);

/* Find table by 4-character signature */
ACPISDTHeader *acpi_find_table(const ACPIManager *mgr, const char *signature);

/* Print all tables in the XSDT for diagnostics */
void acpi_print_tables(const ACPIManager *mgr);

/* Print detailed MADT contents */
void acpi_print_madt(const ACPIMADT *madt);

/* ??? L8: ACPI vs Device Tree Comparison ????????????????????????????? */

/*
 * Both ACPI and FDT provide hardware description to the OS.
 *
 * ACPI (x86, ARM server):
 *   + Power management, hotplug, NUMA
 *   + Vendor-neutral bytecode (AML)
 *   - Complex specification (>1000 pages)
 *   - Runtime interpretation overhead
 *
 * FDT (ARM embedded, RISC-V):
 *   + Simple static tree structure
 *   + No runtime interpretation
 *   - No power management standard
 *   - Board-specific bindings
 *
 * Reference: ARM SBBR mandates ACPI for servers,
 *            ARM EBBR allows FDT for embedded.
 */
void acpi_print_acpi_vs_fdt_comparison(void);

#endif /* ACPI_FW_H */
